name: Auto Commit Daily Random

on:
  schedule:
    - cron: '0 23 * * *'  # Runs daily at 23:00 UTC (midnight Morocco time)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make random commits
        run: |
          COMMITS=$(( ( RANDOM % 21 ) + 20 ))
          echo "Will make $COMMITS commits today."

          for i in $(seq 1 $COMMITS); do
            echo "Commit $i made at $(date)" >> daily_log.txt
            git add daily_log.txt
            git commit -m "Random commit $i at $(date)" || echo "Nothing to commit"
          done

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
